# Generated by Django 2.2.2 on 2019-07-19 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForexAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForexAccount.AccountInfo')),
            ],
        ),
    ]
