# Generated by Django 2.2.2 on 2019-07-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForexAccount', '0003_strategyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolinfo',
            name='bool_select',
            field=models.BooleanField(default=True),
        ),
    ]
